subdir-ccflags-y += -Idrivers/soc/hisense/include

obj-y    += base/

obj-y    += pm/

obj-y    += pmic/

obj-y    += mm/

obj-y    += usb/

obj-y    += debug/

obj-y    += efuse/

obj-y    += security/

obj-y    += sales_name/

obj-y    += abnormal_stats/

obj-y    += rs_recorder/

obj-y    += misc/

obj-y    += audio/

obj-y    += subsystem/

obj-y    += sensor/
